// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
import Link from "next/link";
import Providers from "../providers/providers";
import "./common.min.css";
import getHeader from "@/fetches/getHeader";
// import "https://wp.s9p.ir/wp-includes/css/dist/block-library/common.min.css?ver=6.4.1";
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = await getHeader();
  return (
    <html>
      <head dangerouslySetInnerHTML={{ __html: header }} />
      {/* <head /> */}
      <body>
        {/* {JSON.stringify(header)} */}
        <Link href={"/"}>Home</Link>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
